# Generated by Django 4.2.1 on 2023-05-04 12:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('country', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('street', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('building_number', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
