# Generated by Django 4.2.1 on 2023-05-04 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='confirm_password',
        ),
    ]
