# Generated by Django 4.2.1 on 2023-05-06 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='building_number',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
