# Generated by Django 4.2.1 on 2023-05-08 14:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_paymenttokent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentTokent',
            new_name='PaymentToken',
        ),
    ]
