# Generated by Django 4.2.1 on 2023-05-10 17:34

import cloudinary.models
from django.db import migrations
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, validators=[products.models.validateImage], verbose_name='images'),
            preserve_default=False,
        ),
    ]
